### ISSUE TITLE
There is no EC2 in SimulatedOnPrem stack? 

### ISSUE THREAD

**Issue by entest-hai** [smuralee/network-segmentation-demo#2]
I could not find an EC2 in SImulatedOnPrem stack. So how VPN site-to-site done here?

**Comment by smuralee** [comment]
SimulatedOnPrem stack only creates the VPC. Please use the project https://github.com/aws-samples/vpn-gateway-strongswan for creating the EC2

I have added it as a note in the README

**Comment by entest-hai** [comment]
Thank you! understand now

**Comment by entest-hai** [comment]
@smuralee still struggling to connect the simulated on-premises with VPC via TGW. Do you have any suggestion?

**Comment by smuralee** [comment]
@entest-hai Can you please provide more details on the issue you are facing?

- What does the network reachability say about the simulated VPC and TGW connectivity?
- Is the connectivity failing within the same region or cross region?

**Comment by entest-hai** [comment]
@smuralee 
The issue is between the Simulated On-Premise and a VPC in the same region. 

1. How to setup VPN for the simulated on-premise? I created the simulated on-premise by using a template from [aws openswan networking workshop](https://networking.workshop.aws/beginner/lab2/010_builddc.html). 

2. After the simulated-on premise deployed, how to setup the VPN-TGW-Routable? Need a static route destination 10.10.0.0/16, **stuck in blackhole state** how on-premise can reach VPCs?

3. Your repository does not show how to setup connection between the simulated on-prem and VPCs in AWS

**Comment by entest-hai** [comment]
Finally, I get it working. My error was missing setting up 2 secret keys (PSK) for the strongswan (simulated on-prem) stack. Still have a question. Ping from on-premise to AWS VPC works but reachability analyzer path between on-premise and VPCs does not work in this case (ec2-strongswan)

**Comment by smuralee** [comment]
I had used network reachability analyzer for debugging only. When the project was published the ping was tested from region-1 on-prem simulator EC2 to region-2 on-prem simulator EC2 via Transit Gateway peering.

I will need to read more on this
